@extends('layouts.customerlayout')
@section('index') 
		<h1>Welcome Bangladesh asknfkdjvdnvjfn vfa <a href="#">cdsbj</a></h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
		<h1>Welcome</h1>
@endsection 